<?php
namespace Notoj;
/* do not edit this file */
Notoj::loadCache(array (
  'ea0fc14ce3d69fd520a6790b9d989edb76977053' => 
  array (
  ),
  'da5b5d1813b9b3768b3d5a6a1493505f4e1f5e83' => 
  array (
    0 => 
    array (
      'method' => 'view',
      'args' => 
      array (
        0 => 'Sample/index.tpl',
      ),
    ),
  ),
  '17c7ab1de6b29780286b373849a63ba7b05d0333' => 
  array (
  ),
  '0a1daac0e67b23128fc134e8ddc91136439f1013' => 
  array (
    0 => 
    array (
      'method' => 'View',
      'args' => 
      array (
        0 => 'Test/index.tpl',
      ),
    ),
  ),
  'ba3bd82e3b8eff6ff6f7526d520d99e9d7f2d89f' => 
  array (
    0 => 
    array (
      'method' => 'Response',
      'args' => 
      array (
        'Content-type' => 'application/javascript',
      ),
    ),
    1 => 
    array (
      'method' => 'View',
      'args' => 
      array (
        0 => 'Test/index.tpl',
      ),
    ),
  ),
));
